services:
  caddy:
    build: ./caddy
    ports:
      - "443:443"
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
  dns-pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      DNSMASQ_LISTENING: all
    volumes:
      - './dns-pihole/etc-pihole:/etc/pihole'
      - './dns-pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #ports:
    #- "${PIHOLE_WEB_PORT}:80"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  nextcloud:
    image: nextcloud:latest
    environment:
      - TZ=${TIMEZONE}
      # nextcloud settings
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_HOST}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      # db settings(postgres)
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # for reverse proxy
      - OVERWRITEHOST=${NEXTCLOUD_HOST}
      - OVERWRITEPROTOCOL=https
    depends_on:
      - db
      - caddy
      - dns-pihole
